fix typo

diff --git a/tools/pi/autorun b/tools/pi/autorun
--- a/tools/pi/autorun
+++ b/tools/pi/autorun
@@ -115,7 +115,7 @@ while true; do
     if test -e ~ov/ov-client.hifiberry; then
         HBERRY=$(cat ~ov/ov-client.hifiberry)
         rm -f ~ov/ov-client.hifiberry
-        sudo sed -i -e 's/[^#]*hifiberry-/#&/g' /boot/confix.txt|| echo "unable to disable hifiberry modules"
+        sudo sed -i -e 's/[^#]*hifiberry-/#&/g' /boot/config.txt|| echo "unable to disable hifiberry modules"
         if test "${HBERRY}" != "none"; then
             sudo sed -i -e "/dtoverlay*.hifiberry-${HBERRY}/ d" /boot/config.txt|| echo "unable to add new hifiberry entry"
             (
