improve install scripts

diff --git a/tools/install_pi5 b/tools/install_pi5
--- a/tools/install_pi5
+++ b/tools/install_pi5
@@ -10,23 +10,52 @@
 
 (
     # minimal error handling:
-    trap "echo An error occured.;exit 1" ERR
+    trap "echo An error occured.;sleep 20;exit 1" ERR
 
+    # start in home directory:
     cd
 
     export DEBIAN_FRONTEND=noninteractive
 
+    # update main system
+    # in case someone powered off during installation we need to fix unconfigured packages:
+    sudo dpkg --configure -a
+    sync
+
     echo "update apt database:"
-    sudo -E apt-get update --assume-yes || sudo -E apt-get update --assume-yes
+    # install dependencies:
+    # retry 10 times because the raspios servers are not very stable:
+    cnt=10
+    while test $cnt -gt 0; do
+        echo counter: $cnt
+	sudo -E apt update && cnt=-1 || ( sleep 7; let cnt=$cnt-1 )
+	sync
+    done
+    #sudo -E apt-get update --assume-yes || sudo -E apt-get update --assume-yes
 
     echo "Install CA certificates:"
-    sudo -E apt-get install --no-install-recommends --assume-yes ca-certificates  || sudo -E apt-get install --no-install-recommends --assume-yes ca-certificates
+    cnt=10
+    while test $cnt -gt 0; do
+        echo counter: $cnt
+        sudo -E apt-get install --no-install-recommends --assume-yes ca-certificates && cnt=-1  || ( sleep 7; let cnt=$cnt-1)
+        sync
+    done
 
     echo "install git, build-essential and other basic stuff:"
-    sudo -E apt-get install --no-install-recommends --assume-yes git build-essential cmake xxd gettext-base lsb-release || sudo -E apt-get install --no-install-recommends --assume-yes git build-essential cmake xxd gettext-base lsb-release
+    cnt=10
+    while test $cnt -gt 0; do
+        echo counter: $cnt
+        sudo -E apt-get install --no-install-recommends --assume-yes git build-essential cmake xxd gettext-base lsb-release && cnt=-1   || ( sleep 7; let cnt=$cnt-1 )
+        sync
+    done
 
     echo "install dependencies of cli tool:"
-    sudo -E apt-get install --no-install-recommends --assume-yes liblo-dev libcurl4-openssl-dev libasound2-dev libeigen3-dev libfftw3-dev libfftw3-single3 libgsl-dev libjack-jackd2-dev libltc-dev libmatio-dev libsndfile1-dev libsamplerate0-dev nlohmann-json3-dev libxerces-c-dev libgtkmm-3.0-dev libcairomm-1.0-dev libcunit1-dev
+    cnt=10
+    while test $cnt -gt 0; do
+        echo counter: $cnt
+        sudo -E apt-get install --no-install-recommends --assume-yes liblo-dev libcurl4-openssl-dev libasound2-dev libeigen3-dev libfftw3-dev libfftw3-single3 libgsl-dev libjack-jackd2-dev libltc-dev libmatio-dev libsndfile1-dev libsamplerate0-dev nlohmann-json3-dev libxerces-c-dev libgtkmm-3.0-dev libcairomm-1.0-dev libcunit1-dev && cnt=-1 || ( sleep 7; let cnt=$cnt-1 )
+        sync
+    done
 
     echo "clone or update git repo:"
     (cd ov-client && git clean -ffx && git pull) || git clone https://github.com/gisogrimm/ov-client
@@ -63,6 +92,7 @@
     echo "install autorun script:"
     sudo cp ov-client/tools/pi/autorun_pi5 /home/pi/autorun
     sudo chmod a+x /home/pi/autorun
+    # the next line needs a fix because it works only on the correct system:
     sudo chown pi:pi /home/pi/autorun
 
     echo "register autorun script in /etc/rc.local:"
