initial support for explicit git support

diff --git a/tools/install_pi5 b/tools/install_pi5
--- a/tools/install_pi5
+++ b/tools/install_pi5
@@ -74,36 +74,105 @@ BOOTFS=`mount | grep /boot | sed -e 's/.*\/boot/\/boot/1' -e 's/ .*//1'`
         sync
     done
 
-    echo "install liblsl:"
-    (
-        git clone -b v1.16.2 https://github.com/sccn/liblsl.git || true
-        cd liblsl
-        ./standalone_compilation_linux.sh
-        sudo cp liblsl.so /usr/lib/
-        sudo cp -r include/* /usr/include/
-    ) || true
+    if test -e ${BOOTFS}/ovclient-firmwareupdate-git; then
+	rm -f ${BOOTFS}/ovclient-firmwareupdate-git
+	# install from git repo:
 
-    echo "clone or update git repo:"
-    (cd ov-client && git clean -ffx && git pull) || git clone https://github.com/gisogrimm/ov-client
+	if test ! -e "/usr/include/lsl_c.h"; then
+	    echo "install liblsl:"
+	    (
+		git clone -b v1.16.2 https://github.com/sccn/liblsl.git || true
+		cd liblsl
+		./standalone_compilation_linux.sh
+		sudo cp liblsl.so /usr/lib/
+		sudo cp -r include/* /usr/include/
+	    ) || true
+	fi
+	
+	echo "clone or update git repo:"
+	(cd ov-client && git clean -ffx && git pull) || git clone https://github.com/gisogrimm/ov-client
+	
+	echo "checkout selected branch:"
+	(cd ov-client && git clean -ffx && git checkout $BRANCH && git pull)
+	
+	echo "update submodules:"
+	make -C ov-client gitupdate
+	
+	echo "clean repo:"
+	make -C ov-client clean
+	
+	echo "build tools:"
+	make -j $(nproc) -C ov-client cli
+	
+	echo "package tools:"
+	make -C ov-client/packaging/deb clipack
+	
+	echo "install new debian packages:"
+	sudo -E apt-get install --assume-yes --no-install-recommends ./ov-client/packaging/deb/debian/*/ovbox-cli_*.deb
 
-    echo "move to development version:"
-    (cd ov-client && git clean -ffx && git checkout $BRANCH && git pull)
+    else
+	# install debian packages from apt repo:
+	# retry 10 times because the raspios servers are not very stable:
+	cnt=10
+	while test $cnt -gt 0; do
+	    sudo -E apt update && cnt=-1 || ( sleep 20; let cnt=$cnt-1 )
+	    sync
+	done
+	if test $cnt -eq 0; then
+            echo "failed 10 times, switching to GWDG mirror"
+            sudo sed -i -e '/raspbian/ d' -e '/^[[:blank:]]*$/ d' /etc/apt/sources.list|| echo "unable to remove previous apt entries"
+            (echo "";echo "deb http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian/ ${OSREL} main contrib non-free rpi")|sudo tee -a /etc/apt/sources.list
+            sync
+            cnt=10
+            while test $cnt -gt 0; do
+		sudo -E apt update && cnt=0 || ( sleep 20; let cnt=$cnt-1 )
+		sync
+            done
+	fi
+	cnt=10
+	while test $cnt -gt 0; do
+	    sudo -E apt upgrade --assume-yes && cnt=0 || ( sleep 20; let cnt=$cnt-1 )
+	    sync
+	done
 
-    echo "update submodules:"
-    make -C ov-client gitupdate
+	# identify OS release code name:
+	OSREL=`lsb_release -a|grep Codename|sed 's/Codename:[[:blank:]]*//1'`
+	OSRELHTCH="$OSREL"
+	if test "$OSREL" = "buster"; then
+            OSRELHTCH=bionic
+	fi
+	# identify OS architecture:
+	OSARCH=`dpkg-architecture | grep -e 'DEB_BUILD_ARCH='|sed 's/[^=]*=//1'`
 
-    echo "clean repo:"
-    make -C ov-client clean
 
-    echo "build tools:"
-    make -j $(nproc) -C ov-client cli
+	# add/update HoerTech apt repository (containing ov-client):
+	sudo sed -i -e '/apt.hoertech.de/ d' -e '/^[[:blank:]]*$/ d' /etc/apt/sources.list|| echo "unable to remove previous apt entries"
+	wget -qO- http://apt.hoertech.de/openmha-packaging.pub | sudo apt-key add -
+	(echo "";echo "deb [arch=${OSARCH}] http://apt.hoertech.de ${OSRELHTCH} universe")|sudo tee -a /etc/apt/sources.list
+	sync
 
-    echo "package tools:"
-    make -C ov-client/packaging/deb clipack
-
-    echo "install new debian packages:"
-    sudo -E apt-get install --assume-yes --no-install-recommends ./ov-client/packaging/deb/debian/*/ovbox-cli_*.deb
-
+	# in case someone powered off during installation we need to fix unconfigured packages:
+	sudo dpkg --configure -a
+	sync
+	# install dependencies:
+	# retry 10 times because the raspios servers are not very stable:
+	cnt=10
+	while test $cnt -gt 0; do
+	    sudo -E apt update && cnt=0 || ( sleep 20; let cnt=$cnt-1 )
+	    sync
+	done
+	cnt=10
+	while test $cnt -gt 0; do
+	    sudo -E apt upgrade --assume-yes && cnt=0 || ( sleep 20; let cnt=$cnt-1 )
+	    sync
+	done
+	cnt=10
+	while test $cnt -gt 0; do
+	    sudo -E apt install --no-install-recommends --assume-yes ov-client libnss-mdns && cnt=0 || ( sleep 20; let cnt=$cnt-1 )
+	    sync
+	done
+	
+    fi
     echo "install rtirq-init:"
     sudo -E apt-get install --assume-yes --no-install-recommends rtirq-init
 
